---
title: "p8105_hw5_js5165"
author: "Jingqi Song"
date: "November 7, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
library(tidyverse)

```

## Problem 1
```{r P1}
import_file = function(x){read_csv(paste0('./data/', x))}
observ = list.files('./data/', pattern = '*.csv') %>% 
  map(import_file) %>% 
  reduce(rbind) %>% 
  janitor::clean_names() %>% 
  mutate(seq = seq(from=1, to=20, by=1),
         group = ifelse(seq < 11, c('control'), c('exp')),
         sub = rep(1:10, 2),
         id = paste(group, sub, sep = '_')) %>% 
  gather(key = "week", value = "observation", week_1:week_8) %>%
  select(id, group, week, observation)
  
```

```{r P1 plot}
p1_plot = observ %>% 
  ggplot(aes(x = week, y = observation)) + 
  geom_line(aes(colour = group, group = id)) +
    labs(
    title = "Observations Over Time" ,
    x = "Week" ,
    y = "Observations"
    ) +
  theme(legend.position = "right")
p1_plot
```

